version: '2'
services:
  hazelcast-client:
    image:  dantericalde/hazelcast_client_app
    depends_on:
      - hazelcast
    volumes:
      - ./docker-compose/src/main/resources:/configFolder
    environment:
      - JAVA_OPTS=-Dhazelcast.client.config=/configFolder/hazelcast-client.xml -Dhazelcast.member.address=hazelcast -Dgroup.name=hz-compose -Dgroup.password=s3crEt
    links:
      - management-center:mancenter
  service2:
    image:  dantericalde/service2
    depends_on:
      - hazelcast
    volumes:
      - ./service2/src/main/resources:/configFolder
    environment:
#      - JAVA_OPTS=-Dhazelcast.client.config=/configFolder/hazelcast-client.xml -Dhazelcast.member.address=hazelcast -Dgroup.name=hz-compose -Dgroup.password=s3crEt -Dembedded.group.name=service2 -Dembedded.group.password=service2
      - JAVA_OPTS=-Dhazelcast.client.config=/configFolder/hazelcast-client.xml -Dhazelcast.member.address=hazelcast -Dgroup.name=hz-compose -Dgroup.password=s3crEt
    links:
      - management-center:mancenter
  hazelcast:
    image:  hazelcast/hazelcast
    volumes:
      - ./docker-compose/src/main/resources/member:/configFolder
    environment:
      - JAVA_OPTS=-Dhazelcast.config=/configFolder/hazelcast.xml -Dhazelcast.mancenter.url=http://mancenter:8080/mancenter -Dgroup.name=hz-compose -Dgroup.password=s3crEt
    links:
      - management-center:mancenter
  management-center:
    image:  hazelcast/management-center:3.8.2
    container_name: management-center
    volumes:
      - ~/mancenter3.8:/mancenter-3.8
    environment:
      - MANCENTER_DATA=/mancenter-3.8
      - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true
    ports:
      - 8080:8080
      